SEED:
  random_seed: 3307
DATALOADER:
  shuffle: true

TRAIN:
  batch_size: 16
  learning_rate: 0.0001
  eps: 1e-08
  weight_decay: [0.01]
  num_warmup_step: 15
  epochs: 50
  threshold: 0.5
  early_stop: 10
